# Disable metrics - we stick to the sabre coding
Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/OptionalArguments:
  Enabled: false

# ['word', 'array'] looks better when aligned with other arrays that can't use
# %w() syntax
Style/WordArray:
  Enabled: false
